#!/bin/bash
# DarkScraper smart scaling - generates docker-compose.override.yml dynamically
# Usage: SCALE_LEVEL=5 ./start.sh

set -e

SCALE_LEVEL=${SCALE_LEVEL:-3}

echo "🎚️  Starting DarkScraper with SCALE_LEVEL=$SCALE_LEVEL"

# Calculate instances
TOR_COUNT=$((SCALE_LEVEL * 2))
[ $TOR_COUNT -gt 10 ] && TOR_COUNT=10
I2P_COUNT=$SCALE_LEVEL
[ $I2P_COUNT -gt 5 ] && I2P_COUNT=5
HYPHANET_COUNT=$SCALE_LEVEL
[ $HYPHANET_COUNT -gt 3 ] && HYPHANET_COUNT=3
LOKINET_COUNT=$SCALE_LEVEL
[ $LOKINET_COUNT -gt 4 ] && LOKINET_COUNT=4

echo "📊 Generating: Tor=$TOR_COUNT, I2P=$I2P_COUNT, Hyphanet=$HYPHANET_COUNT, Lokinet=$LOKINET_COUNT instances"

# Generate docker-compose.override.yml with extra instances
cat > docker-compose.override.yml << 'EOF_HEADER'
# Auto-generated by start.sh - DO NOT EDIT MANUALLY
# This file is regenerated each time you run ./start.sh
services:
EOF_HEADER

# Generate Tor instances 6-10 if needed
for i in $(seq 6 $TOR_COUNT); do
  cat >> docker-compose.override.yml << EOF
  tor$i:
    image: osminogin/tor-simple:latest
    volumes:
      - tor${i}data:/var/lib/tor
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 9050 2>/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

EOF
done

# Generate I2P instances 6-10 if needed
for i in $(seq 6 $I2P_COUNT); do
  cat >> docker-compose.override.yml << EOF
  i2p$i:
    build: ./docker/i2p
    environment:
      JVM_XMX: 768m
      IP_ADDR: 0.0.0.0
    volumes:
      - i2p${i}data:/i2p/.i2p
    healthcheck:
      test: ["CMD-SHELL", "wget --spider --timeout=10 http://127.0.0.1:7657/ 2>&1 | grep -q '200 OK' || exit 1"]
      interval: 30s
      timeout: 15s
      retries: 30
      start_period: 600s

EOF
done

# Add volumes section
cat >> docker-compose.override.yml << 'EOF'
volumes:
EOF

for i in $(seq 6 $TOR_COUNT); do
  echo "  tor${i}data:" >> docker-compose.override.yml
done

for i in $(seq 6 $I2P_COUNT); do
  echo "  i2p${i}data:" >> docker-compose.override.yml
done

echo ""
echo "✅ Generated docker-compose.override.yml with $((TOR_COUNT + I2P_COUNT + HYPHANET_COUNT + LOKINET_COUNT)) instances"

# Export env vars - calculate workers based on SCALE_LEVEL
export SCALE_LEVEL

# Instances
export TOR_INSTANCES=$TOR_COUNT
export I2P_INSTANCES=$I2P_COUNT
export HYPHANET_INSTANCES=$HYPHANET_COUNT
export LOKINET_INSTANCES=$LOKINET_COUNT

# Workers (calculated from SCALE_LEVEL)
TOR_WORKERS=$(case $SCALE_LEVEL in 1) echo 16;; 2) echo 48;; 3) echo 64;; 4) echo 96;; 5) echo 128;; *) echo 32;; esac)
I2P_WORKERS=$((SCALE_LEVEL * 4))
HYPHANET_WORKERS=$((SCALE_LEVEL * 2))
[ $HYPHANET_WORKERS -gt 12 ] && HYPHANET_WORKERS=12
LOKINET_WORKERS=$((SCALE_LEVEL * 4))
[ $LOKINET_WORKERS -gt 20 ] && LOKINET_WORKERS=20

export TOR_WORKERS
export I2P_WORKERS
export HYPHANET_WORKERS
export LOKINET_WORKERS

echo "⚙️  Workers: Tor=$TOR_WORKERS, I2P=$I2P_WORKERS, Hyphanet=$HYPHANET_WORKERS, Lokinet=$LOKINET_WORKERS"

# Start (profiles removed - all handled by SCALE_LEVEL)
echo "🚀 Starting docker-compose..."
docker compose up
